### ISSUE TITLE
User authentication failed

### ISSUE THREAD

**Issue by WildChen** [easemob/chat-android#95]
后台申请appkey后，验证码登录提示：User authentication failed

**Comment by jinanzhuan** [comment]
> 后台申请appkey后，验证码登录提示：User authentication failed

验证码登录是为了方便用户体验，对特定的appkey搭建的app server。您如果要源码体验 Demo 的话，建议将登录方式修改为 UserId + password/token 的方式，并移除 app server 部分的逻辑。

**Comment by liuxucool163** [comment]
怎么修改登录方式呢？

**Comment by jinanzhuan** [comment]
> 怎么修改登录方式呢？

可以参考官方文档：http://docs-im-beta.easemob.com/document/android/overview.html#%E6%89%8B%E5%8A%A8%E7%99%BB%E5%BD%95
将手机号+验证码改成用户名和密码就行。
用户名和密码获取的方式，可以参考“注册用户”：http://docs-im-beta.easemob.com/document/android/overview.html#%E6%B3%A8%E5%86%8C%E7%94%A8%E6%88%B7
如果您对于如何修改还有其他问题，可以继续留言。

**Comment by tmac1999** [comment]
Process: com.hyphenate.chatdemo, PID: 8885
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.hyphenate.chat.adapter.EMAError com.hyphenate.chat.adapter.EMAChatClient.createAccount(java.lang.String, java.lang.String)' on a null object reference
        at com.hyphenate.chat.EMClient.createAccount(Unknown Source:22)
        at com.hyphenate.chatdemo.section.login.fragment.LoginFragment.onClick(LoginFragment.java:295)
        at android.view.View.performClick(View.java:7535)
        at android.view.View.performClickInternal(View.java:7512)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29496)
        at android.os.Handler.handleCallback(Handler.java:984)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:357)
        at android.app.ActivityThread.main(ActivityThread.java:8155)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

注册用户也报错 ，请问你们在写demo的时候自己测过吗
